name: 'Package size report'

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  package-size-report:
    name: üîß Build all packages [${{ matrix.os }}, Node ${{ matrix.node }}]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['17.9.0']
    steps:
      - name: üõéÔ∏è Checkout repo
        uses: actions/checkout@v3
      - name: ‚öôÔ∏è Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.SA_ARTIFACT_REGISTRY_WRITER }}
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0
      - name: ‚öôÔ∏è Refresh access token for Artifact Registry
        run: npx google-artifactregistry-auth --repo-config .npmrc --verbose
      - name: Package size report
        # https://github.com/marketplace/actions/pkg-size-action
        uses: pkg-size/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
