name: 'size-report'

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  package-size-report:
    name: ğŸ”§ Build all packages [${{ matrix.os }}, Node.js ${{ matrix.node }}]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['current']
    steps:
      - name: ğŸ›ï¸ Check out repo
        uses: actions/checkout@v3

      - name: âš™ï¸ Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: âš™ï¸ Install dependencies
        run: npm ci

      - name: ğŸ”§ Build libraries
        run: npm run build:libs

      - name: ğŸ“ Package size report
        run: npm run size

      # Why is this so slow? It went from a couple of minutes to 8 minutes, then
      # to more than 13 minutes!
      # - name: ğŸ“ Package size report
      #   # https://github.com/marketplace/actions/pkg-size-action
      #   uses: pkg-size/action@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     build-command: 'npm run build'
      #     comment-report: true
      #     display-size: 'uncompressed'
      #     # ignore all docs generated by TypeDoc, but not the ones generated by
      #     # api-extractor + api-documenter (because they are useful when doing
      #     # API design review)
      #     hide-files: 'docs/**'
      #     # hide-files: '*.{css,js,ts}.map'
